### ISSUE TITLE
Configuration files

### ISSUE THREAD

**Issue by jozefg** [david-christiansen/jonprl-mode#26]
JonPRL now supports "configuration files", just files which specify JonPRL files and other configuration files. It'd be cool if JonPRL mode understood how to use configuration files, but I'm not sure what a good interface for handling them would be, any thoughts?

_[PR adding config support to JonPRL](https://github.com/jonsterling/JonPRL/pull/175)_

**Comment by david-christiansen** [comment]
Presumably, the `.cfg` files can just get the same commands and keybindings for loading as in `.jonprl` files, right?

They should probably have completion of file names as well.

**Comment by jonsterling** [comment]
@david-christiansen Sure, that makes sense; I think, though, that it is important that you be able to load a configuration file, and then work on individual files within a development. Then, I would want `C-l` (or some shortcut) to apply to the configuration file, not necessarily to the file I'm in. This is because the file won't make sense on its own, since it will likely depend on the other modules in the development.

Unlike most systems like Coq or Agda, where they have import statements in developments, we have followed the Twelf approach and kept that out of the development language and left the way that developments are composed open-ended.

In Twelf-mode, which is pretty reasonable, you always have to select a configuration file before you can begin checking developments. It might be a bit more user friendly if we, however, made this optional. But I don't feel too strongly either way.

**Comment by david-christiansen** [comment]
That makes sense. Here's an implementation suggestion:
1. Add a new buffer-local variable called `jonprl-configuration-file`. If it's `nil` or `shut-up`, then there's no config, and JonPRL should get the current file as an argument. If it's a string, then JonPRL will get that filename as its argument instead.
2. Have the load commands check the status of `jonprl-configuration-file`. If it's `nil`, do the following:
   - If there's a `.cfg` file in the current directory or one of its super-directories, prompt the user for a config file with this file as the default
   - If there is no `.cfg` file, prompt the the user with no default. Use filename completion in each case.
   - If the user selects a file, store it in `jonprl-configuration-file` and use it from here on out. If the user does not select a file, do the following:
     - If there was a `.cfg` file, ask the user (using `y-or-n-p`) if they'd like to ignore the config file. If they say yes, set the variable to `shut-up`. If they say no, load the source file this time but leave the variable as `nil`.
     - If there was no `.cfg` file, then just set the variable to `shut-up` immediately.

Also, there should be a `jonprl-forget-configuration` command to reset the variable without reopening the file.

How does this sound?

**Comment by jonsterling** [comment]
that sounds like a good plan! I'll fiddle with it this weekend.

**Comment by david-christiansen** [comment]
If you get to it before me, there's code in `idris-ipkg-mode` for walking upward after a file and using it to prompt with default filename arguments. It can probably be straightforwardly adapted for that part.

**Comment by jonsterling** [comment]
I'm making some progress on this code, but had a question...

I'm using `(read-file-name ...)`, and I expect the desired behavior is, if the user escapes out of the minibuffer, we set the variable to `shut-up`. But, when the user escapes from the minibuffer, it appears that the rest of my function is not executed. I was hoping that `read-file-name` would just return `nil` at that point, but maybe that's not how it works...

**Comment by david-christiansen** [comment]
Escaping the minibuffer (presumably with `C-g`) throws an exception that you should handle. But I'd have a blank input mean non, and escaping mean "cancel" - that's a more ordinary Emacs interface, where "bail" usually cancels everything
